language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - boost-latest
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - clang-3.7
      - libboost1.55-all-dev
      - libopencv-dev
before_script:
  - if [ "$CXX" = "g++" ]; then export CXX=/usr/bin/g++-5; fi
  - if [ "$CXX" = "clang++" ]; then export CXX=/usr/bin/clang++-3.7; fi
script: cmake . && make
